exclude_paths:
- ".meteor/*"
- "packages/reaction-core-theme/lib/*"
- "packages/reaction-core/lib/*"
- "packages/reaction-ui/private/*"
- "packages/reaction-ui-navbar/private/*"
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        javascript:
          mass_threshold: 150

  eslint:
    enabled: true
  csslint:
    enabled: false
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
ratings:
   paths:
   - "**.js"
   - "**.jsx"
   - "**.css"
