services:
- name: reaction-core
  root_domain: staging.reactioncommerce.com
  dns_name: reaction-core
  desired_task_count: 2
  min_task_count: 0
  max_task_count: 2
  min_healthy_percent: 100
  max_percent: 200
  alb_listener_port: 80
  alb_listener_path: /
  alb_health_check_path: /health
  task-definition:
    name: staging-core
    containers:
    - name: core
      cpu: 500
      memory: 1800
      port_mappings:
      - container_port: 3000
        host_port: 3000
      image: reactioncommerce/reaction
      image_tag: release-2.0.0-rc.7
      env_params:
      - name: REACTION_AUTH
      - name: REACTION_EMAIL
      - name: REACTION_USER
      - name: MONGO_URL
      - name: ROOT_URL
      - name: HYDRA_ADMIN_URL
      - name: HYDRA_OAUTH2_INTROSPECT_URL
      - name: SKIP_FIXTURES
      - name: CERTIFICATE_ARN
- name: storefront-core
  root_domain: staging.reactioncommerce.com
  dns_name: storefront
  desired_task_count: 1
  min_task_count: 0
  max_task_count: 2
  min_healthy_percent: 100
  max_percent: 200
  alb_listener_port: 80
  alb_listener_path: /
  alb_health_check_path: /health
  task-definition:
    name: staging-storefront-core
    containers:
    - name: nginx
      cpu: 128
      memory: 256
      port_mappings:
      - container_port: 8082
        host_port: 8082
      image: reactioncommerce/reaction-nginx
      image_tag: storefront
      links:
      - storefront
      env_params:
      - name: PROXY_URL
      - name: NGINX_LISTEN_PORT
      - name: CERTIFICATE_ARN
    - name: storefront
      cpu: 500
      memory: 1800
      port_mappings:
      - container_port: 4000
      image: reactioncommerce/reaction-next-starterkit
      image_tag: develop
      env_params:
      - name: INTERNAL_GRAPHQL_URL
      - name: EXTERNAL_GRAPHQL_URL
      - name: FAVICON_URL
      - name: PLACEHOLDER_IMAGE_URL_GALLERY
      - name: PLACEHOLDER_IMAGE_URL_GRID
      - name: SEGMENT_ANALYTICS_SKIP_MINIMIZE
      - name: SEGMENT_ANALYTICS_WRITE_KEY
      - name: KEYCLOAK_REALM
      - name: KEYCLOAK_CLIENT_ID
      - name: KEYCLOAK_URL
      - name: KEYCLOAK_REDIRECT_URI
      - name: STRIPE_PUBLIC_API_KEY
      - name: OAUTH2_AUTH_URL
      - name: OAUTH2_TOKEN_URL
      - name: OAUTH2_CLIENT_ID
      - name: OAUTH2_CLIENT_SECRET
      - name: OAUTH2_REDIRECT_URL
      - name: OAUTH2_HOST
      - name: OAUTH2_ADMIN_PORT
      - name: HYDRA_ADMIN_URL
      - name: SESSION_SECRET
      - name: SESSION_MAX_AGE_MS
      - name: CANONICAL_URL
