#!/bin/bash
#

# copy clone-packages.sh so that any directory
# can be specified for use in PACKAGE_DIRS config.
cp bin/clone-packages.sh /usr/local/bin/

#
# by default runs settings/dev.settings.json
# customize by creating settings/settings.json
bin/run --raw-logs
