export default {
  Account: "reaction/account",
  Address: "reaction/address",
  CatalogItem: "reaction/catalogItem",
  CatalogProduct: "reaction/catalogProduct",
  CatalogProductVariant: "reaction/catalogProductVariant",
  Cart: "reaction/cart",
  CartItem: "reaction/cartItem",
  Currency: "reaction/currency",
  FulfillmentGroup: "reaction/fulfillmentGroup",
  FulfillmentMethod: "reaction/fulfillmentMethod",
  Group: "reaction/group",
  NavigationItem: "reaction/navigationItem",
  NavigationTree: "reaction/navigationTree",
  Order: "reaction/order",
  OrderFulfillmentGroup: "reaction/orderFulfillmentGroup",
  OrderItem: "reaction/orderItem",
  Payment: "reaction/payment",
  Product: "reaction/product",
  Role: "reaction/role",
  Shop: "reaction/shop",
  Tag: "reaction/tag"
};
