export { default as ProductDetail } from "./productDetail";
export { default as Social } from "./social";
export { default as VariantList } from "./variantList";
export { default as ChildVariant } from "./childVariant";
export { default as AddToCartButton } from "./addToCartButton";
export { default as MediaGallery } from "./mediaGallery";
export { default as ProductMetadata } from "./metadata";
export { default as ProductTags } from "./tags";
export { default as ProductField } from "./productField";
