export default [
  {
    label: "العربية",
    value: "ar"
  }, {
    label: "Български",
    value: "bg"
  }, {
    label: "中文(简体)",
    value: "zh"
  }, {
    label: "České",
    value: "cs"
  }, {
    label: "Deutsch",
    value: "de"
  }, {
    label: "English",
    value: "en"
  }, {
    label: "Ελληνικά",
    value: "el"
  }, {
    label: "Español",
    value: "es"
  }, {
    label: "Français",
    value: "fr"
  }, {
    label: "עברית",
    value: "he"
  }, {
    label: "Hrvatski",
    value: "hr"
  }, {
    label: "မြန်မာဘာသာ",
    value: "my"
  }, {
    label: "Italiano",
    value: "it"
  }, {
    label: "Nederlands",
    value: "nl"
  }, {
    label: "Norsk bokmål",
    value: "nb"
  }, {
    label: "Polski",
    value: "pl"
  }, {
    label: "Português",
    value: "pt"
  }, {
    label: "Русский",
    value: "ru"
  }, {
    label: "Română",
    value: "ro"
  }, {
    label: "Slovenščina",
    value: "sl"
  }, {
    label: "Svenska",
    value: "sv"
  }, {
    label: "Türkçe",
    value: "tr"
  }, {
    label: "tiếng Việt",
    value: "vi"
  }
];
