export const testData = [
  {"carrier":1,"enabled":true,"label":"Itaperuçu","name":"Brazil"},
  {"carrier":2,"enabled":false,"label":"Shanga","name":"Nigeria"},
  {"carrier":3,"enabled":false,"label":"Rochester","name":"United States"},
  {"carrier":4,"enabled":false,"label":"Maragogipe","name":"Brazil"},
  {"carrier":5,"enabled":false,"label":"Mwembe","name":"Tanzania"},
  {"carrier":6,"enabled":false,"label":"Kárystos","name":"Greece"},
  {"carrier":7,"enabled":false,"label":"Halmstad","name":"Sweden"},
  {"carrier":8,"enabled":true,"label":"Knoxville","name":"United States"},
  {"carrier":9,"enabled":true,"label":"Uruçuca","name":"Brazil"},
  {"carrier":10,"enabled":false,"label":"Bollène","name":"France"},
  {"carrier":11,"enabled":false,"label":"Černý Most","name":"Czech Republic"},
  {"carrier":12,"enabled":false,"label":"Soufrière","name":"Dominica"},
  {"carrier":13,"enabled":false,"label":"Zakamensk","name":"Russia"},
  {"carrier":14,"enabled":false,"label":"Barentu","name":"Eritrea"},
  {"carrier":15,"enabled":true,"label":"Buga","name":"Colombia"},
  {"carrier":16,"enabled":false,"label":"Baranoa","name":"Colombia"},
  {"carrier":17,"enabled":true,"label":"Taubaté","name":"Brazil"},
  {"carrier":18,"enabled":false,"label":"Podgorenskiy","name":"Russia"},
  {"carrier":19,"enabled":true,"label":"Milwaukee","name":"United States"},
  {"carrier":20,"enabled":false,"label":"Huangqiang","name":"China"},
  {"carrier":21,"enabled":true,"label":"Nyanza","name":"Rwanda"},
  {"carrier":22,"enabled":true,"label":"Boljevac","name":"Serbia"},
  {"carrier":23,"enabled":false,"label":"Damiku","name":"China"},
  {"carrier":24,"enabled":true,"label":"Xushan","name":"China"},
  {"carrier":25,"enabled":false,"label":"Henggouqiao","name":"China"},
  {"carrier":26,"enabled":false,"label":"Rancakuya","name":"Indonesia"},
  {"carrier":27,"enabled":true,"label":"Sumberrejo","name":"Indonesia"},
  {"carrier":28,"enabled":true,"label":"Karanggeneng","name":"Indonesia"},
  {"carrier":29,"enabled":false,"label":"General José de San Martín","name":"Argentina"},
  {"carrier":30,"enabled":false,"label":"Xiaolongmen","name":"China"},
  {"carrier":31,"enabled":false,"label":"Starcevica","name":"Bosnia and Herzegovina"},
  {"carrier":32,"enabled":false,"label":"Payao","name":"Philippines"},
  {"carrier":33,"enabled":true,"label":"Jawornik","name":"Poland"},
  {"carrier":34,"enabled":true,"label":"Yudai","name":"China"},
  {"carrier":35,"enabled":true,"label":"Huaranchal","name":"Peru"},
  {"carrier":36,"enabled":false,"label":"Mtubatuba","name":"South Africa"},
  {"carrier":37,"enabled":false,"label":"Tanahbeureum","name":"Indonesia"},
  {"carrier":38,"enabled":false,"label":"Strassen","name":"Luxembourg"},
  {"carrier":39,"enabled":true,"label":"Maintirano","name":"Madagascar"},
  {"carrier":40,"enabled":false,"label":"Vostochnoe Degunino","name":"Russia"},
  {"carrier":41,"enabled":true,"label":"Čeladná","name":"Czech Republic"},
  {"carrier":42,"enabled":true,"label":"Chigang","name":"China"},
  {"carrier":43,"enabled":false,"label":"Pataha","name":"Indonesia"},
  {"carrier":44,"enabled":true,"label":"Qijiawan","name":"China"},
  {"carrier":45,"enabled":false,"label":"‘Ābūd","name":"Palestinian Territory"},
  {"carrier":46,"enabled":false,"label":"Peliyagoda","name":"Sri Lanka"},
  {"carrier":47,"enabled":true,"label":"Hošťka","name":"Czech Republic"},
  {"carrier":48,"enabled":true,"label":"Zográfos","name":"Greece"},
  {"carrier":49,"enabled":false,"label":"Tsowkêy","name":"Afghanistan"},
  {"carrier":50,"enabled":false,"label":"Huangchi","name":"China"},
  {"carrier":51,"enabled":false,"label":"Pingshi","name":"China"},
  {"carrier":52,"enabled":true,"label":"Song","name":"Thailand"},
  {"carrier":53,"enabled":true,"label":"Colcabamba","name":"Peru"},
  {"carrier":54,"enabled":false,"label":"Delod Pangkung","name":"Indonesia"},
  {"carrier":55,"enabled":true,"label":"Iwanuma","name":"Japan"},
  {"carrier":56,"enabled":false,"label":"Carodok","name":"Indonesia"},
  {"carrier":57,"enabled":false,"label":"Sobotka","name":"Czech Republic"},
  {"carrier":58,"enabled":false,"label":"South River","name":"Canada"},
  {"carrier":59,"enabled":false,"label":"Aiguo","name":"China"},
  {"carrier":60,"enabled":true,"label":"Kajiado","name":"Kenya"},
  {"carrier":61,"enabled":true,"label":"El Paso","name":"United States"},
  {"carrier":62,"enabled":false,"label":"Capalonga","name":"Philippines"},
  {"carrier":63,"enabled":false,"label":"Omoku","name":"Nigeria"},
  {"carrier":64,"enabled":true,"label":"Przemków","name":"Poland"},
  {"carrier":65,"enabled":true,"label":"Soljani","name":"Croatia"},
  {"carrier":66,"enabled":true,"label":"Bofuer","name":"Indonesia"},
  {"carrier":67,"enabled":true,"label":"Sattahip","name":"Thailand"},
  {"carrier":68,"enabled":true,"label":"Qingchuan","name":"China"},
  {"carrier":69,"enabled":true,"label":"Anzihao","name":"China"},
  {"carrier":70,"enabled":true,"label":"Houston","name":"United States"},
  {"carrier":71,"enabled":false,"label":"Lombo Meão","name":"Portugal"},
  {"carrier":72,"enabled":false,"label":"Świebodzice","name":"Poland"},
  {"carrier":73,"enabled":true,"label":"Santa Bárbara","name":"Guatemala"},
  {"carrier":74,"enabled":false,"label":"East London","name":"South Africa"},
  {"carrier":75,"enabled":true,"label":"Papilawe","name":"Indonesia"},
  {"carrier":76,"enabled":false,"label":"Baishui","name":"China"},
  {"carrier":77,"enabled":false,"label":"Sanyi","name":"China"},
  {"carrier":78,"enabled":false,"label":"Mangunjaya","name":"Indonesia"},
  {"carrier":79,"enabled":false,"label":"Borås","name":"Sweden"},
  {"carrier":80,"enabled":true,"label":"Kedrovyy","name":"Russia"},
  {"carrier":81,"enabled":true,"label":"Ijero-Ekiti","name":"Nigeria"},
  {"carrier":82,"enabled":true,"label":"Otuzco","name":"Peru"},
  {"carrier":83,"enabled":false,"label":"Burtunay","name":"Russia"},
  {"carrier":84,"enabled":false,"label":"Thị Trấn Phú Mỹ","name":"Vietnam"},
  {"carrier":85,"enabled":true,"label":"Gelan","name":"China"},
  {"carrier":86,"enabled":true,"label":"Louredo","name":"Portugal"},
  {"carrier":87,"enabled":true,"label":"Vazante","name":"Brazil"},
  {"carrier":88,"enabled":false,"label":"Gimbi","name":"Ethiopia"},
  {"carrier":89,"enabled":false,"label":"Al Ḩayfah","name":"Yemen"},
  {"carrier":90,"enabled":true,"label":"Lere","name":"Nigeria"},
  {"carrier":91,"enabled":false,"label":"Calapan","name":"Philippines"},
  {"carrier":92,"enabled":true,"label":"Menlou’ao","name":"China"},
  {"carrier":93,"enabled":false,"label":"Llorente","name":"Philippines"},
  {"carrier":94,"enabled":false,"label":"Stalbe","name":"Latvia"},
  {"carrier":95,"enabled":true,"label":"Shestakovo","name":"Russia"},
  {"carrier":96,"enabled":false,"label":"Babakan","name":"Indonesia"},
  {"carrier":97,"enabled":false,"label":"General Levalle","name":"Argentina"},
  {"carrier":98,"enabled":true,"label":"Dve Mogili","name":"Bulgaria"},
  {"carrier":99,"enabled":false,"label":"Neiva","name":"Colombia"},
  {"carrier":100,"enabled":false,"label":"Oekero","name":"Indonesia"}
];
